import {
  IonButton,
  IonContent,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonSegment,
  IonSegmentButton,
  IonSegmentContent,
  IonSegmentView,
  IonText,
  IonIcon,
  IonCheckbox,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCol,
  IonRow,
  IonButtons,
  IonBackButton,
  IonGrid,
  IonToast,
  IonFooter,
  IonBadge,
  IonCardSubtitle,
  IonListHeader,
  IonAvatar,
  IonTextarea,
  IonSelectOption,
  IonSelect,
  IonRadio,
  IonRadioGroup,
  IonDatetime,
  IonDatetimeButton,
  IonModal,
  IonPopover,
  IonChip,
  IonNote,
} from '@ionic/angular/standalone';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HeaderComponent } from './components/header/header.component';
import { FormField } from '@angular/forms/signals';
import { CommonModule } from '@angular/common';

export const SHARED_MODULES = [
  IonButton,
  IonContent,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonSegment,
  IonSegmentButton,
  IonSegmentView,
  IonSegmentContent,
  IonText,
  IonIcon,
  IonCheckbox,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCol,
  IonRow,
  IonButtons,
  IonBackButton,
  IonGrid,
  IonToast,
  FormsModule,
  ReactiveFormsModule,
  IonFooter,
  IonBadge,
  IonCardSubtitle,
  IonListHeader,
  IonAvatar,
  IonSelect,
  IonSelectOption,
  IonTextarea,
  IonRadioGroup,
  IonRadio,
  IonCheckbox,
  IonDatetime,
  IonDatetimeButton,
  IonModal,
  IonPopover,
  IonChip,  
  IonNote,
  // FORMS
  FormField,
  // CommonModule
  CommonModule
] as const;

export const SHARED_COMPONENTS = [HeaderComponent] as const;
